import { GoogleOAuthProvider } from '@react-oauth/google';
import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import Footer from '@/components/layout/public/Footer';
import Header from '@/components/layout/public/Header';
import { Toaster } from '@/components/ui/toast';
import { cn } from '@/lib/utils';
import { AuthProvider } from '@/providers/auth.provider';
import QueryProvider from '@/providers/query.provider';
import './globals.css';

const inter = Inter({
    subsets: ['latin'],
    variable: '--font-sans',
});

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'SR HealthCare',
    description: 'Generated by SR HealthCare',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const clientID = process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID;

    const content = (
        <QueryProvider>
            <AuthProvider>
                <div className="flex min-h-screen flex-col">
                    <Header />

                    <main className="flex-1">{children}</main>

                    <Toaster />

                    <Footer />
                </div>
            </AuthProvider>
        </QueryProvider>
    );

    return (
        <html
            lang="en"
            className={cn(
                'h-full',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'font-sans',
                inter.variable,
            )}
        >
            <body>
                {clientID ? (
                    <GoogleOAuthProvider clientId={clientID}>
                        {content}
                    </GoogleOAuthProvider>
                ) : (
                    content
                )}
            </body>
        </html>
    );
}
