import type { Metadata } from 'next';
import { Geist, Geist_Mono, Inter } from 'next/font/google';
import './globals.css';
import Footer from '@/components/layout/public/Footer';
import Header from '@/components/layout/public/Header';
import { Toaster } from '@/components/ui/toast';
import { cn } from '@/lib/utils';
import QueryProvider from '@/providers/query.provider';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const geistSans = Geist({
    variable: '--font-geist-sans',
    subsets: ['latin'],
});

const geistMono = Geist_Mono({
    variable: '--font-geist-mono',
    subsets: ['latin'],
});

export const metadata: Metadata = {
    title: 'SR HealthCare',
    description: 'Generated by SR HealthCare',
};

export default function RootLayout({ children }: LayoutProps<'/'>) {
    return (
        <html
            lang="en"
            className={cn(
                'h-full',
                'antialiased',
                geistSans.variable,
                geistMono.variable,
                'font-sans',
                inter.variable,
            )}
        >
            <body>
                <QueryProvider>
                    <div className="flex min-h-screen flex-col">
                        <Header />

                        <main className="flex-1">{children}</main>

                        <Toaster />

                        <Footer />
                    </div>
                </QueryProvider>
            </body>
        </html>
    );
}
